{% set name = "confluence-publisher" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: v{{ version }}

source:
  url: https://github.com/Arello-Mobile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1c6a5fd6a2190121761208535723f6fcedbc88d66244c93aa5a4a676dc7216fd

build:
  noarch: python
  noarch: python
  number: 0
  entry_points:
    - conf_page_dumper = conf_publisher.page_dumper:main
    - conf_page_maker = conf_publisher.page_maker:main
    - conf_publisher = conf_publisher.publish:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyyaml >=3.11
    - requests >=2.4.3

test:
  imports:
    - conf_publisher
    - conf_publisher.page_dumper
    - conf_publisher.page_maker
    - conf_publisher.publish
  commands:
    - conf_page_dumper --help
    - conf_page_maker --help
    - conf_publisher --help

about:
  home: https://github.com/Arello-Mobile/confluence-publisher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Set of tools to help publish documentation to Confluence.'

  description: |
    This tools are written as part of our Documentation Toolkit which
    we use in our job daily. The main idea of toolkit is to make a process
    of creating and updating documentation able to be automated.
  doc_url: https://github.com/Arello-Mobile/confluence-publisher
  dev_url: https://github.com/Arello-Mobile/confluence-publisher

extra:
  recipe-maintainers:
    - CurtLH
