travis:
  secure:
    BINSTAR_TOKEN: l9fCsHDovR+7Xq9ldYtYkCWdkW0SAQRSDQkvDW2iwAU/aezJ/RIDJP3YBQxSTuH+KZdaCiEfqTMqaVHvZ4TVqjKWU9baTjkB6edmnigjfRBPm9Uo96oGbeUPVNPSgw9dCM7NG5EcPI6U9oUbeBCFkFR2d5hDTqKJEaBxIhiAZGNUkb7sYwQOxvjxaHvmKyR3s4wtzzMzyCn7V3fTxkSBMD7r3RC6CwSJYmWUb8aK9LI7j+Tkt2/kUykTZoL47KwIThSbyGqEkFbglrsdO6rszFbXNduc+d8JJ1OfSd7Nb36WEjTVPCpzpVn4Cc4Jj1d6lk5KTUyy8+Xi3UA/lqFG9xECcoFVoEM41WSDE01ohx2qyuv2P6J/qbW2v5RUnXwFtlXWPSiPyDqNq/r9nlzwLWtR8ewj2bKY8ucCerLGVK6/Afm0D6BS9MdGb5g3POiYGAfmIfLukr0Rhmuo90NL0FpkoL4R4JKmg87AJetp7ZdwYpPjTc8nFnhu4Lif3O5U/woeh4QFb4ekM/UuSud5QeGWR6ZwrqEjWwIObxEGLpzg3G4x1BLzGCQfTBjT5PRT2RzOEf9dUUa5P7QTv0COmf9meM0WtvetFDsZrWdkf2lQdYCwCcgV6g9yHPwaUUGm1rfAqx31GyLcoMn8LuE1nFjSav3X1ZILj8c6a1bHuUs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
