travis:
  secure:
    BINSTAR_TOKEN: rIwqbTr0oekeN66x8l7HPjhoUzElwYfE0GsSEfXi+F+A1c2dvNfmBN8O0DodEn+9+E2yv0cofEwt6OmYa7hK25q8aP63dgkSYxsXNcmJ2iTB0T4rao0u5olSwMCKgSx5yCLZwP6apiSh8BTCeEa9EbRD8lfG1saAmZwdpTIbk1kKLLGzHrc3rHjyin/VWZtRhlTr3jnemhHeArQNqB2JbgPNadKtxAntMOLQmcK1TDgAwPU9R6JXHoqqVcL8w0KllmdYOCnwFf4mWeKyWPW3LpT5Y7RLwsxm10IGPNEceh+XPMPIf+mf+ZvQgjGJ7JFT9BkJRYKnbeUplS6qVd/1Rb7lC57BEDEenZGq+511SvRnXvCgf1wQ7OEcykkqD0pDsZbRrpHbZhvMhxc3t1S6Yw/Goo+b+S1XELqaxvRB2o2cLSaG46ipXQ8/cpte31D+uAZ+wcLt3crxHqnAu7gp1md7ZlNhaEPoKLdyF25JwtETwV2W1IdM8ZfnhztXWBz+3caPluqtFbUe2i9pkNWbFgN875SJyG52KcyB9PXsl0rDDrEBYzLnQoYolzfayv4tVeWiCLx5KIAdKHF1SBLtbBrKYysAZh4k5jeBoLGcYnUkf/N+zgRRhyxqjBKlBqQXdh2ETJqKy0KUd//CSqKUg2OHmeAwaQa0iXGXGnm1srk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
